### ISSUE TITLE
Reset Wifi does not seem to work

### ISSUE THREAD

**Issue by Draftdog** [mhendriks/DSMR-API-V2#2]
When using the `Reset Wifi` button on the `Reset en Update` page I'm not getting the expected page:

1. I have the P1 dongle properly working, it says I'm using version `3.5.0+1058 (17/06/2022)`
2. I go to http://dsmr-api.local/#Reset and tap on the `Reset Wifi` Button 
3. I'm still able to use the webpage as before, I was expecting to see the screen with which I can configure my network connection
4. the blue led indicator is continuously on, unlike the situation when I first connected the dongle to my network
5. I cannot see the `P1 Dongle` Wifi network
6. software/hardware restarts do not help the situation
7. I tried updating the firmware to version 3.5.1 via the tarball download from this repo's releases, but this did not seem to do anything

**Comment by mhendriks** [comment]
thanks for reporting. Well found.
Issue in the 3.5.0 version. Solved in 3.5.1 
The 3.5.1 is available as an alpha version.
