### ISSUE TITLE
MQTT authentication doesn't work with special characters.

### ISSUE THREAD

**Issue by MaT-dg** [mhendriks/DSMR-API-V2#3]
When using special characters (I had an '%' and '@') in the MQTT password, authentication on the broker fails.

Broker used: mosquitto.

**Comment by MaT-dg** [comment]
The problem seems to be the UTF-8 encoding of special characters in the POST request.

'!' becomes '%21'
'#' becomes '%23'
'$' becomes '%24'
..and so on.

Since the '%' in my random long password was converted to '%25' I took me a while to spot it.
A solution could be the rejection of these characters in the input field or decoding the UTF-8 encoded request before saving the new value.

This affects all input fields btw, not only the MQTT password field.

**Comment by mhendriks** [comment]
Issue with the pro version frontend.
Has been solved in the last frontend fix (4.5.2). Use the 4.5.0 firmware + DSMRIndexEdge.html with link tot the 4.5 cdn.
