### ISSUE TITLE
Not updates in ota.smart-stuff.nl

### ISSUE THREAD

**Issue by RneeJ** [mhendriks/DSMR-API-V2#5]
I originally bought the Esp home version of the P1 meter (not pro) but later updated it to DSMR-API version, for use with Domoticz. 

All worked well for some months but suddely the web interface started displaying only totals instead of per day value's. 
The correct date is retrieved from the P1 port, but all data are cumulated to the previous days. 

I tried updating to the latest version witch didn't work. I ended up with version 3.5.0.
It works with Domoticz.

The webinterface doesn't work anymore, error from http://myip : 
```
FileNotFound
```

Updating, via Telnet,  to 3.5.10 is not possible because :
```
!!! OTA UPDATE !!!
Update type: File
OTA versie 3.5.10 | flashsize 4 Mb
OTA path: http://ota.smart-stuff.nl/DSMR-API-V3.5.10_4Mb.spiffs.bin
HTTP update fatal error code -102 | File Not Found (404)
```

How can i download the latest complete version ?
How do i restore the webinterface ?

I'am not interested in saving history, because that is in Domoticz.

Dank je.

**Comment by mhendriks** [comment]
Hi RneeJ,

Is it the P1 Dongle or P1 Dongle Pro?
The latest version for the P1 Dongle is the 3.5.9. It could be downloaded via : https://ota.smart-stuff.nl/DSMR-API-V3.5.9_4Mb.bin

**Comment by RneeJ** [comment]
The problem is part of the name 'spiffs' which is added automaticly.

I only enter version 3.5.9 the rest is added by the programm.

Please add the correct file name:

https://ota.smart-stuff.nl/DSMR-API-V3.5.9_4Mb.spiffs.bin

**Comment by mhendriks** [comment]
clear, done.

**Comment by RneeJ** [comment]
Thank you, everything works again including webinterface,  on version 3.5.9.
